name: backend-cd

on:
  pull_request:
    branches: [ "dev" ]
    types: [closed]
    
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 8.8

    - name: Grant execute permission for gradlew
      run: chmod +x backend/bang-ggood/gradlew

    - name: Write application.yml
      env:
        APPLICATION_YML: ${{ secrets.APPLICATION_YML }}
        APPLICATION_TEST_YML: ${{ secrets.APPLICATION_TEST_YML }}
      run: |
        echo "${APPLICATION_YML}" > src/main/resources/application.yml
        echo "${APPLICATION_TEST_YML}" > src/test/resources/application-test.yml

    - name: Build with Gradle
      run: ./gradlew clean build
      working-directory: backend/bang-ggood

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        working-directory: backend/bang-ggood
        name: bang-ggood-be-develop-jar
        path: ./**/*.jar

  deploy:
    needs: build
    runs-on: bang-ggood
    steps:
      - name: change permission
        run: sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/2024-bang-ggood

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: bang-ggood-be-develop-jar

      - name: Turn off the server 8080 if runs
        run: sudo fuser -k -n tcp 8080 || true

      - name: Start server
        run: sudo nohup java -jar ./backend/bang-ggood/build/libs/*SNAPSHOT.jar &
